import { ref, onMounted } from 'vue'

export const countryCallingCodes = [
  // { country: 'Afghanistan', country_code: 'AF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/af.svg' },
  // { country: 'Albania', country_code: 'AL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/al.svg' },
  // { country: 'Algeria', country_code: 'DZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/dz.svg' },
  // { country: 'American Samoa', country_code: 'AS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/as.svg' },
  // { country: 'Andorra', country_code: 'AD', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ad.svg' },
  // { country: 'Angola', country_code: 'AO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ao.svg' },
  // { country: 'Anguilla', country_code: 'AI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ai.svg' },
  // { country: 'Antarctica', country_code: 'AQ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/aq.svg' },
  // { country: 'Antigua and Barbuda', country_code: 'AG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ag.svg' },
  // { country: 'Argentina', country_code: 'AR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ar.svg' },
  // { country: 'Armenia', country_code: 'AM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/am.svg' },
  // { country: 'Aruba', country_code: 'AW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/aw.svg' },
  { country: 'Australia', country_code: 'AU', calling_code: '+61', flag: 'https://cdn.ipwhois.io/flags/au.svg' },
  // { country: 'Austria', country_code: 'AT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/at.svg' },
  // { country: 'Azerbaijan', country_code: 'AZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/az.svg' },
  // { country: 'Bahamas', country_code: 'BS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bs.svg' },
  // { country: 'Bahrain', country_code: 'BH', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bh.svg' },
  // { country: 'Bangladesh', country_code: 'BD', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bd.svg' },
  // { country: 'Barbados', country_code: 'BB', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bb.svg' },
  // { country: 'Belarus', country_code: 'BY', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/by.svg' },
  // { country: 'Belgium', country_code: 'BE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/be.svg' },
  // { country: 'Belize', country_code: 'BZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bz.svg' },
  // { country: 'Benin', country_code: 'BJ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bj.svg' },
  // { country: 'Bermuda', country_code: 'BM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bm.svg' },
  // { country: 'Bhutan', country_code: 'BT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bt.svg' },
  // { country: 'Bolivia, Plurinational State of', country_code: 'BO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bo.svg' },
  // { country: 'Bonaire, Sint Eustatius and Saba', country_code: 'BQ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bq.svg' },
  // { country: 'Bosnia and Herzegovina', country_code: 'BA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ba.svg' },
  // { country: 'Botswana', country_code: 'BW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bw.svg' },
  // { country: 'Bouvet Island', country_code: 'BV', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bv.svg' },
  // { country: 'Brazil', country_code: 'BR', calling_code: '+55', flag: 'https://cdn.ipwhois.io/flags/br.svg' },
  // { country: 'British Indian Ocean Territory', country_code: 'IO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/io.svg' },
  // { country: 'Brunei Darussalam', country_code: 'BN', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bn.svg' },
  // { country: 'Bulgaria', country_code: 'BG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bg.svg' },
  // { country: 'Burkina Faso', country_code: 'BF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bf.svg' },
  // { country: 'Burundi', country_code: 'BI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bi.svg' },
  // { country: 'Cabo Verde', country_code: 'CV', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cv.svg' },
  // { country: 'Cambodia', country_code: 'KH', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/kh.svg' },
  // { country: 'Cameroon', country_code: 'CM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cm.svg' },
  // { country: 'Canada', country_code: 'CA', calling_code: '+1', flag: 'https://cdn.ipwhois.io/flags/ca.svg' },
  // { country: 'Cayman Islands', country_code: 'KY', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ky.svg' },
  // { country: 'Central African Republic', country_code: 'CF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cf.svg' },
  // { country: 'Chad', country_code: 'TD', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/td.svg' },
  // { country: 'Chile', country_code: 'CL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cl.svg' },
  { country: 'China', country_code: 'CN', calling_code: '+86', flag: 'https://cdn.ipwhois.io/flags/cn.svg' },
  // { country: 'Christmas Island', country_code: 'CX', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cx.svg' },
  // { country: 'Cocos (Keeling) Islands', country_code: 'CC', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cc.svg' },
  // { country: 'Colombia', country_code: 'CO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/co.svg' },
  // { country: 'Comoros', country_code: 'KM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/km.svg' },
  // { country: 'Congo', country_code: 'CG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cg.svg' },
  // { country: 'Congo, The Democratic Republic of the', country_code: 'CD', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cd.svg' },
  // { country: 'Cook Islands', country_code: 'CK', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ck.svg' },
  // { country: 'Costa Rica', country_code: 'CR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cr.svg' },
  // { country: 'Croatia', country_code: 'HR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/hr.svg' },
  // { country: 'Cuba', country_code: 'CU', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cu.svg' },
  // { country: 'Curaçao', country_code: 'CW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cw.svg' },
  // { country: 'Cyprus', country_code: 'CY', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cy.svg' },
  // { country: 'Czechia', country_code: 'CZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/cz.svg' },
  // { country: 'Côte dIvoire', country_code: 'CI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ci.svg' },
  // { country: 'Denmark', country_code: 'DK', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/dk.svg' },
  // { country: 'Djibouti', country_code: 'DJ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/dj.svg' },
  // { country: 'Dominica', country_code: 'DM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/dm.svg' },
  // { country: 'Dominican Republic', country_code: 'DO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/do.svg' },
  // { country: 'Ecuador', country_code: 'EC', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ec.svg' },
  // { country: 'Egypt', country_code: 'EG', calling_code: '+20', flag: 'https://cdn.ipwhois.io/flags/eg.svg' },
  // { country: 'El Salvador', country_code: 'SV', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sv.svg' },
  // { country: 'Equatorial Guinea', country_code: 'GQ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gq.svg' },
  // { country: 'Eritrea', country_code: 'ER', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/er.svg' },
  // { country: 'Estonia', country_code: 'EE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ee.svg' },
  // { country: 'Eswatini', country_code: 'SZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sz.svg' },
  // { country: 'Ethiopia', country_code: 'ET', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/et.svg' },
  // { country: 'Falkland Islands (Malvinas)', country_code: 'FK', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/fk.svg' },
  // { country: 'Faroe Islands', country_code: 'FO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/fo.svg' },
  // { country: 'Fiji', country_code: 'FJ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/fj.svg' },
  // { country: 'Finland', country_code: 'FI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/fi.svg' },
  // { country: 'France', country_code: 'FR', calling_code: '+33', flag: 'https://cdn.ipwhois.io/flags/fr.svg' },
  // { country: 'French Guiana', country_code: 'GF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gf.svg' },
  // { country: 'French Polynesia', country_code: 'PF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pf.svg' },
  // { country: 'French Southern Territories', country_code: 'TF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tf.svg' },
  // { country: 'Gabon', country_code: 'GA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ga.svg' },
  // { country: 'Gambia', country_code: 'GM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gm.svg' },
  // { country: 'Georgia', country_code: 'GE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ge.svg' },
  // { country: 'Germany', country_code: 'DE', calling_code: '+49', flag: 'https://cdn.ipwhois.io/flags/de.svg' },
  // { country: 'Ghana', country_code: 'GH', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gh.svg' },
  // { country: 'Gibraltar', country_code: 'GI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gi.svg' },
  // { country: 'Greece', country_code: 'GR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gr.svg' },
  // { country: 'Greenland', country_code: 'GL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gl.svg' },
  // { country: 'Grenada', country_code: 'GD', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gd.svg' },
  // { country: 'Guadeloupe', country_code: 'GP', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gp.svg' },
  // { country: 'Guam', country_code: 'GU', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gu.svg' },
  // { country: 'Guatemala', country_code: 'GT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gt.svg' },
  // { country: 'Guernsey', country_code: 'GG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gg.svg' },
  // { country: 'Guinea', country_code: 'GN', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gn.svg' },
  // { country: 'Guinea-Bissau', country_code: 'GW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gw.svg' },
  // { country: 'Guyana', country_code: 'GY', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gy.svg' },
  // { country: 'Haiti', country_code: 'HT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ht.svg' },
  // { country: 'Heard Island and McDonald Islands', country_code: 'HM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/hm.svg' },
  // { country: 'Holy See (Vatican City State)', country_code: 'VA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/va.svg' },
  // { country: 'Honduras', country_code: 'HN', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/hn.svg' },
  // { country: 'Hong Kong', country_code: 'HK', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/hk.svg' },
  // { country: 'Hungary', country_code: 'HU', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/hu.svg' },
  // { country: 'Iceland', country_code: 'IS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/is.svg' },
  { country: 'India', country_code: 'IN', calling_code: '+91', flag: 'https://cdn.ipwhois.io/flags/in.svg' },
  { country: 'Indonesia', country_code: 'ID', calling_code: '+62', flag: 'https://cdn.ipwhois.io/flags/id.svg' },
  // { country: 'Iran, Islamic Republic of', country_code: 'IR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ir.svg' },
  // { country: 'Iraq', country_code: 'IQ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/iq.svg' },
  // { country: 'Ireland', country_code: 'IE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ie.svg' },
  // { country: 'Isle of Man', country_code: 'IM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/im.svg' },
  // { country: 'Israel', country_code: 'IL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/il.svg' },
  // { country: 'Italy', country_code: 'IT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/it.svg' },
  // { country: 'Jamaica', country_code: 'JM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/jm.svg' },
  { country: 'Japan', country_code: 'JP', calling_code: '+81', flag: 'https://cdn.ipwhois.io/flags/jp.svg' },
  // { country: 'Jersey', country_code: 'JE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/je.svg' },
  // { country: 'Jordan', country_code: 'JO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/jo.svg' },
  // { country: 'Kazakhstan', country_code: 'KZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/kz.svg' },
  // { country: 'Kenya', country_code: 'KE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ke.svg' },
  // { country: 'Kiribati', country_code: 'KI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ki.svg' },
  // { country: 'Korea, Democratic Peoples Republic of', country_code: 'KP', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/kp.svg' },
  { country: 'Korea, Republic of', country_code: 'KR', calling_code: '+82', flag: 'https://cdn.ipwhois.io/flags/kr.svg' },
  // { country: 'Kuwait', country_code: 'KW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/kw.svg' },
  // { country: 'Kyrgyzstan', country_code: 'KG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/kg.svg' },
  // { country: 'Lao Peoples Democratic Republic', country_code: 'LA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/la.svg' },
  // { country: 'Latvia', country_code: 'LV', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/lv.svg' },
  // { country: 'Lebanon', country_code: 'LB', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/lb.svg' },
  // { country: 'Lesotho', country_code: 'LS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ls.svg' },
  // { country: 'Liberia', country_code: 'LR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/lr.svg' },
  // { country: 'Libya', country_code: 'LY', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ly.svg' },
  // { country: 'Liechtenstein', country_code: 'LI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/li.svg' },
  // { country: 'Lithuania', country_code: 'LT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/lt.svg' },
  // { country: 'Luxembourg', country_code: 'LU', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/lu.svg' },
  // { country: 'Macao', country_code: 'MO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mo.svg' },
  // { country: 'Madagascar', country_code: 'MG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mg.svg' },
  // { country: 'Malawi', country_code: 'MW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mw.svg' },
  { country: 'Malaysia', country_code: 'MY', calling_code: '+60', flag: 'https://cdn.ipwhois.io/flags/my.svg' },
  // { country: 'Maldives', country_code: 'MV', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mv.svg' },
  // { country: 'Mali', country_code: 'ML', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ml.svg' },
  // { country: 'Malta', country_code: 'MT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mt.svg' },
  // { country: 'Marshall Islands', country_code: 'MH', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mh.svg' },
  // { country: 'Martinique', country_code: 'MQ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mq.svg' },
  // { country: 'Mauritania', country_code: 'MR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mr.svg' },
  // { country: 'Mauritius', country_code: 'MU', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mu.svg' },
  // { country: 'Mayotte', country_code: 'YT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/yt.svg' },
  // { country: 'Mexico', country_code: 'MX', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mx.svg' },
  // { country: 'Micronesia, Federated States of', country_code: 'FM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/fm.svg' },
  // { country: 'Moldova, Republic of', country_code: 'MD', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/md.svg' },
  // { country: 'Monaco', country_code: 'MC', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mc.svg' },
  // { country: 'Mongolia', country_code: 'MN', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mn.svg' },
  // { country: 'Montenegro', country_code: 'ME', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/me.svg' },
  // { country: 'Montserrat', country_code: 'MS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ms.svg' },
  // { country: 'Morocco', country_code: 'MA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ma.svg' },
  // { country: 'Mozambique', country_code: 'MZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mz.svg' },
  // { country: 'Myanmar', country_code: 'MM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mm.svg' },
  // { country: 'Namibia', country_code: 'NA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/na.svg' },
  // { country: 'Nauru', country_code: 'NR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/nr.svg' },
  // { country: 'Nepal', country_code: 'NP', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/np.svg' },
  // { country: 'Netherlands', country_code: 'NL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/nl.svg' },
  // { country: 'New Caledonia', country_code: 'NC', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/nc.svg' },
  // { country: 'New Zealand', country_code: 'NZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/nz.svg' },
  // { country: 'Nicaragua', country_code: 'NI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ni.svg' },
  // { country: 'Niger', country_code: 'NE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ne.svg' },
  // { country: 'Nigeria', country_code: 'NG', calling_code: '+234', flag: 'https://cdn.ipwhois.io/flags/ng.svg' },
  // { country: 'Niue', country_code: 'NU', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/nu.svg' },
  // { country: 'Norfolk Island', country_code: 'NF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/nf.svg' },
  // { country: 'North Macedonia', country_code: 'MK', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mk.svg' },
  // { country: 'Northern Mariana Islands', country_code: 'MP', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mp.svg' },
  // { country: 'Norway', country_code: 'NO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/no.svg' },
  // { country: 'Oman', country_code: 'OM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/om.svg' },
  // { country: 'Pakistan', country_code: 'PK', calling_code: '+92', flag: 'https://cdn.ipwhois.io/flags/pk.svg' },
  // { country: 'Palau', country_code: 'PW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pw.svg' },
  // { country: 'Palestine, State of', country_code: 'PS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ps.svg' },
  // { country: 'Panama', country_code: 'PA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pa.svg' },
  // { country: 'Papua New Guinea', country_code: 'PG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pg.svg' },
  // { country: 'Paraguay', country_code: 'PY', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/py.svg' },
  // { country: 'Peru', country_code: 'PE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pe.svg' },
  { country: 'Philippines', country_code: 'PH', calling_code: '+63', flag: 'https://cdn.ipwhois.io/flags/ph.svg' },
  // { country: 'Pitcairn', country_code: 'PN', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pn.svg' },
  // { country: 'Poland', country_code: 'PL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pl.svg' },
  // { country: 'Portugal', country_code: 'PT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pt.svg' },
  // { country: 'Puerto Rico', country_code: 'PR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pr.svg' },
  // { country: 'Qatar', country_code: 'QA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/qa.svg' },
  // { country: 'Romania', country_code: 'RO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ro.svg' },
  // { country: 'Russian Federation', country_code: 'RU', calling_code: '+7', flag: 'https://cdn.ipwhois.io/flags/ru.svg' },
  // { country: 'Rwanda', country_code: 'RW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/rw.svg' },
  // { country: 'Réunion', country_code: 'RE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/re.svg' },
  // { country: 'Saint Barthélemy', country_code: 'BL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/bl.svg' },
  // { country: 'Saint Helena, Ascension and Tristan da Cunha', country_code: 'SH', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sh.svg' },
  // { country: 'Saint Kitts and Nevis', country_code: 'KN', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/kn.svg' },
  // { country: 'Saint Lucia', country_code: 'LC', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/lc.svg' },
  // { country: 'Saint Martin (French part)', country_code: 'MF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/mf.svg' },
  // { country: 'Saint Pierre and Miquelon', country_code: 'PM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/pm.svg' },
  // { country: 'Saint Vincent and the Grenadines', country_code: 'VC', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/vc.svg' },
  // { country: 'Samoa', country_code: 'WS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ws.svg' },
  // { country: 'San Marino', country_code: 'SM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sm.svg' },
  // { country: 'Sao Tome and Principe', country_code: 'ST', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/st.svg' },
  { country: 'Saudi Arabia', country_code: 'SA', calling_code: '+966', flag: 'https://cdn.ipwhois.io/flags/sa.svg' },
  // { country: 'Senegal', country_code: 'SN', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sn.svg' },
  // { country: 'Serbia', country_code: 'RS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/rs.svg' },
  // { country: 'Seychelles', country_code: 'SC', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sc.svg' },
  // { country: 'Sierra Leone', country_code: 'SL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sl.svg' },
  { country: 'Singapore', country_code: 'SG', calling_code: '+65', flag: 'https://cdn.ipwhois.io/flags/sg.svg' },
  // { country: 'Sint Maarten (Dutch part)', country_code: 'SX', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sx.svg' },
  // { country: 'Slovakia', country_code: 'SK', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sk.svg' },
  // { country: 'Slovenia', country_code: 'SI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/si.svg' },
  // { country: 'Solomon Islands', country_code: 'SB', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sb.svg' },
  // { country: 'Somalia', country_code: 'SO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/so.svg' },
  // { country: 'South Africa', country_code: 'ZA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/za.svg' },
  // { country: 'South Georgia and the South Sandwich Islands', country_code: 'GS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/gs.svg' },
  // { country: 'South Sudan', country_code: 'SS', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ss.svg' },
  // { country: 'Spain', country_code: 'ES', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/es.svg' },
  // { country: 'Sri Lanka', country_code: 'LK', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/lk.svg' },
  // { country: 'Sudan', country_code: 'SD', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sd.svg' },
  // { country: 'Suriname', country_code: 'SR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sr.svg' },
  // { country: 'Svalbard and Jan Mayen', country_code: 'SJ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sj.svg' },
  // { country: 'Sweden', country_code: 'SE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/se.svg' },
  // { country: 'Switzerland', country_code: 'CH', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ch.svg' },
  // { country: 'Syrian Arab Republic', country_code: 'SY', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/sy.svg' },
  // { country: 'Taiwan, Province of China', country_code: 'TW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tw.svg' },
  // { country: 'Tajikistan', country_code: 'TJ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tj.svg' },
  // { country: 'Tanzania, United Republic of', country_code: 'TZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tz.svg' },
  { country: 'Thailand', country_code: 'TH', calling_code: '+66', flag: 'https://cdn.ipwhois.io/flags/th.svg' },
  // { country: 'Timor-Leste', country_code: 'TL', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tl.svg' },
  // { country: 'Togo', country_code: 'TG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tg.svg' },
  // { country: 'Tokelau', country_code: 'TK', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tk.svg' },
  // { country: 'Tonga', country_code: 'TO', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/to.svg' },
  // { country: 'Trinidad and Tobago', country_code: 'TT', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tt.svg' },
  // { country: 'Tunisia', country_code: 'TN', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tn.svg' },
  // { country: 'Turkey', country_code: 'TR', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tr.svg' },
  // { country: 'Turkmenistan', country_code: 'TM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tm.svg' },
  // { country: 'Turks and Caicos Islands', country_code: 'TC', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tc.svg' },
  // { country: 'Tuvalu', country_code: 'TV', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/tv.svg' },
  // { country: 'Uganda', country_code: 'UG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ug.svg' },
  // { country: 'Ukraine', country_code: 'UA', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ua.svg' },
  // { country: 'United Arab Emirates', country_code: 'AE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ae.svg' },
  { country: 'United Kingdom', country_code: 'GB', calling_code: '+44', flag: 'https://cdn.ipwhois.io/flags/gb.svg' },
  { country: 'United States', country_code: 'US', calling_code: '+1', flag: 'https://cdn.ipwhois.io/flags/us.svg' },
  // { country: 'United States Minor Outlying Islands', country_code: 'UM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/um.svg' },
  // { country: 'Uruguay', country_code: 'UY', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/uy.svg' },
  // { country: 'Uzbekistan', country_code: 'UZ', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/uz.svg' },
  // { country: 'Vanuatu', country_code: 'VU', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/vu.svg' },
  // { country: 'Venezuela, Bolivarian Republic of', country_code: 'VE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ve.svg' },
  { country: 'Viet Nam', country_code: 'VN', calling_code: '+84', flag: 'https://cdn.ipwhois.io/flags/vn.svg' },
  // { country: 'Virgin Islands, British', country_code: 'VG', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/vg.svg' },
  // { country: 'Virgin Islands, U.S.', country_code: 'VI', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/vi.svg' },
  // { country: 'Wallis and Futuna', country_code: 'WF', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/wf.svg' },
  // { country: 'Western Sahara', country_code: 'EH', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/eh.svg' },
  // { country: 'Yemen', country_code: 'YE', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ye.svg' },
  // { country: 'Zambia', country_code: 'ZM', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/zm.svg' },
  // { country: 'Zimbabwe', country_code: 'ZW', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/zw.svg' },
  // { country: 'Åland Islands', country_code: 'AX', calling_code: '', flag: 'https://cdn.ipwhois.io/flags/ax.svg' },
];

export const useCountry = () => {
  const currentCountry = ref<string | null>(null)
  const currentCallingCode = ref<string | null>(null)
  const currentFlag = ref<string | null>(null)

  const detectCountry = async () => {
    try {
      const res = await fetch('https://ipwho.is')
      const data = await res.json()

      if (data.success) {
        currentCountry.value = data.country
        
        const found = countryCallingCodes.find(c => c.country_code === data.country_code)
        
        currentCallingCode.value = found?.calling_code ?? `+${data.calling_code}`
        currentFlag.value = found?.flag ?? `https://cdn.ipwhois.io/flags/${data.country_code.toLowerCase()}.svg`
      } else {
        console.error('Failed to detect country:', data.message)
      }
    } catch (error) {
      console.error('Error detecting country:', error)
    }
  }

  onMounted(() => {
    detectCountry()
  })

  return {
    currentCountry,
    currentCallingCode,
    currentFlag,
    countryCallingCodes
  }
}
