name: Deploy to server
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Login to registry.smartiv.my.id
        uses: docker/login-action@v3
        with:
          registry: registry.smartiv.my.id
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build Docker Images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: registry.smartiv.my.id/saas-cms-client:latest
      - 
        name: Update Service via Webhook
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
      - 
        name: Clean unused docker images
        run: |
          docker image prune -a -f
